### PR TITLE
Remove panning bindings

### PR DESCRIPTION
**Pull request by padenot**
This is being removed from cubeb, in favor in doing it manually by users.

---
This change is [Reviewable](https://reviewable.io/reviews/djg/cubeb-rs/44)

### CODE REVIEW

**Comment by padenot** [comment]
Main cubeb PR: https://github.com/kinetiknz/cubeb/pull/532

**Comment by padenot** [comment]
@kinetiknz, can you have a look ? I can't formally ask for review here.

**Comment by kinetiknz** [comment]
I'll publish a version bump shortly.

**Comment by kinetiknz** [comment]
I see cubeb-coreaudio-rs has a PR ready: https://github.com/ChunMinChang/cubeb-coreaudio-rs/pull/10

We'll need to fix up https://github.com/djg/cubeb-pulse-rs too.

**Comment by kinetiknz** [comment]
cubeb-rs 0.6.0 is published with these changes now.

**Comment by kinetiknz** [comment]
> We'll need to fix up https://github.com/djg/cubeb-pulse-rs too.

https://github.com/djg/cubeb-pulse-rs/pull/46

**Pull request merged**
